### ISSUE TITLE
Superbuild fails

### ISSUE THREAD

**Issue by reckbo** [pnlbwh/ukftractography#74]
I've been getting this error recently.

    git clone https://github.com/pnlbwh/ukftractography
    mkdir build && cd build
    cmake ../ukftractography
    make

```
CMake Error at CMakeLists.txt:74 (message):
  CMAKE_RUNTIME_OUTPUT_DIRECTORY is set to a non-existing directory
  [/tmp/build/bin]


-- Configuring incomplete, errors occurred!
See also "/tmp/build/teem-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/build/teem-build/CMakeFiles/CMakeError.log".
make[2]: *** [teem-prefix/src/teem-stamp/teem-configure] Error 1
make[1]: *** [CMakeFiles/teem.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ihnorton** [comment]
What OS? What version of CMake? This error happens because the build script [sets the `CMAKE_RUNTIME_OUTPUT_DIRECTORY` variable](https://github.com/pnlbwh/ukftractography/blob/999f14d68df59512b2c8f01e4a485eee9008b75b/Common.cmake#L99), but apparently does not create that directory on your system. (maybe it exists? permissions issue?)

I just tested cmake 2.8 and 3.7 on Linux (eris cluster), and 3.6 on Mac, and could not reproduce.

**Comment by ihnorton** [comment]
Hmm, I guess this wouldn't happen until later in the build because of dependencies so I should probably run it for longer. I usually run `make -j2` or more, so maybe some other build step creates `[superbuild]/bin` first. Perhaps with single-process build the ordering is such that teem tries to build before which ever other step creates the directory. I guess we could add an explicit step to create the directory.

**Comment by ihnorton** [comment]
Fix tested on linux and mac, and committed.
